import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="py-3 px-8">
          <header className="flex w-full justify-between my-2 ">
            <h1 className=" font-bold text-xl">
              <Link href={'/'}>Jin`s blog</Link>
            </h1>
            <nav className="flex justify-around font-semiBold text-xs">
              <Link href={'/'} className=" pr-2">
                home
              </Link>
              <Link href={'/about'} className=" pr-2">
                about
              </Link>
              <Link href={'/posts'} className=" pr-2">
                posts
              </Link>
              <Link href={'/contact'} className=" pr-2">
                contact
              </Link>
            </nav>
          </header>
          <main>{children}</main>

          <footer className="bg-black text-white font text-[6px] p-1 mt-5 text-center relative top-3">
            <p className="w-full">
              Don`t forgert to CODE your DREAM | All Right Reserved.
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}
